version: '3.8'

services:
  db:
    image: postgres
    container_name: colmado_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: colmado
    ports:
      - "5432:5432"
